export const Categories = [
    { icon: "thumbs-up", label: "Cleaning" },
    { icon: "hammer", label: "Repairing" },
    { icon: "paint-brush", label: "Painting" },
    { icon: "th-large", label: "More" },
  ]

  export const AllCategories = [
    { icon: "hand-sparkles", label: "Cleaning" },
    { icon: "hammer", label: "Repairing" },
    { icon: "paint-brush", label: "Painting" },
    { icon: "th-large", label: "Welding" },
    { icon: "plug", label: "Electrical Work" },
    { icon: "tint", label: "Plumbing" },
    { icon: "leaf", label: "Gardening" },
    { icon: "bed", label: "Furniture Assembly" },
    { icon: "crosshairs", label: "AC Installation" },
    { icon: "fire", label: "Gas Installation" },
    { icon: "wrench", label: "General Handyman" },
    { icon: "utensils", label: "Kitchen Repairs" },
    { icon: "lock", label: "Locksmith" },
    { icon: "tv", label: "TV Mounting" },
    { icon: "mobile", label: "Appliance Repair" },
    { icon: "car", label: "Car Wash" },
    { icon: "bug", label: "Pest Control" },
    { icon: "broom", label: "Deep Cleaning" },
    { icon: "bolt", label: "Generator Repair" },
    { icon: "fan", label: "Fan Installation" },
    { icon: "desktop", label: "CCTV Installation" },
    { icon: "wifi", label: "Wi-Fi Setup" },
    { icon: "home", label: "House Renovation" },
    { icon: "truck", label: "Moving Services" },
    { icon: "window-maximize", label: "Window Fixing" },
    { icon: "fan", label: "Ceiling Repairs" },
    { icon: "bath", label: "Bathroom Repairs" },
    { icon: "door-closed", label: "Door Installation" },
    { icon: "clock", label: "Routine Maintenance" },
    { icon: "warehouse", label: "Window Cleaning" },
    { icon: "dolly-flatbed", label: "Lawn Mowing" },
    { icon: "lightbulb", label: "Light Fixture Installation" }
  ];
  